# Generated by Django 6.0 on 2025-12-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_no',
            new_name='sid',
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
