# Generated by Django 6.0 on 2025-12-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_roll_no_student_sid_student_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='sname',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
